spring:
  application:
    name: PatientService
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/telecom
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka: 
  client: 
    enabled: true
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:9090/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    home-page-url: http://eureka:9090/
    hostname: localhost
    
    
server:
  port: ${portno:9193}
  